"""T-027 - apply a situational profile.

Three profiles ship, and deliberately not a per-chip matrix: the variance that
matters is backend x chassis x resolution x macOS build, not the model name on
the lid. Applying a profile writes only things CS2Kit is entitled to write -
an environment script, a launch-options line, an `autoexec`-style cfg and the
CS2Video.txt workaround. It never touches a game binary (T-021).
"""
from __future__ import annotations

import json
import os
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

from cs2kit import probe, recipe as recipe_mod
from cs2kit.util import (EXIT_NOT_READY, EXIT_OK, PASS, WARN, Check, emit_error,
                         state_dir, wineprefix, write_json)

CFG_NAME = "cs2kit.cfg"


def env_script_path(name: str) -> Path:
    return state_dir() / "env" / f"{name}.sh"


def active_path() -> Path:
    return state_dir() / "active-profile.json"


def active() -> Dict[str, Any]:
    try:
        return json.loads(active_path().read_text())
    except (OSError, ValueError):
        return {}


def render_env_script(rec: recipe_mod.Recipe) -> str:
    import shlex

    lines = [
        "#!/usr/bin/env bash",
        f"# Generated by cs2kit config apply {rec.name} - do not edit; edit the profile.",
        f"# source this before launching, or use `cs2kit launch --profile {rec.name}`",
        f'export WINEPREFIX="${{WINEPREFIX:-{shlex.quote(str(wineprefix()))}}}"',
    ]
    for key, value in sorted(rec.env.items()):
        # Values come from a YAML file anyone may have written; quote them so a
        # `"; <command>` inside a value stays inert when the script is sourced.
        # $VAR references are expanded here (the way `play` expands them), not
        # left for the shell: inside shlex's single quotes a literal $HOME would
        # survive sourcing and `mkdir -p "$DXMT_SHADER_CACHE"` would create a
        # directory literally named `$HOME`.
        if not key.isidentifier():
            raise recipe_mod.RecipeError(
                f"env key {key!r} is not a valid shell variable name")
        lines.append(f"export {key}={shlex.quote(os.path.expandvars(str(value)))}")
    if rec.launch_options:
        lines.append(f"export CS2KIT_LAUNCH_OPTIONS={shlex.quote(' '.join(rec.launch_options))}")
    if "DXMT_SHADER_CACHE" in rec.env:
        # DXMT will not create it, and a missing directory brings the warning back.
        lines.append('mkdir -p "$DXMT_SHADER_CACHE"')
    return "\n".join(lines) + "\n"


def render_cfg(rec: recipe_mod.Recipe) -> str:
    cvars = rec.data.get("cvars") or {}
    disp = rec.display
    lines = [f"// Generated by cs2kit config apply {rec.name}",
             "// Loaded from autoexec.cfg with: exec cs2kit",
             f"// provenance: {json.dumps(rec.data.get('provenance') or {}, sort_keys=True)}"]
    for key, value in sorted(cvars.items()):
        lines.append(f'{key} "{value}"')
    if disp.get("width") and disp.get("height"):
        lines.append(f'// resolution {disp["width"]}x{disp["height"]} '
                     f'(hidpi {"on" if disp.get("hidpi") else "off"}) - set in the video menu')
    lines.append("host_writeconfig")
    return "\n".join(lines) + "\n"


#: Where CS2 actually reads its video settings from under Wine is UNCONFIRMED:
#: the black-screen workaround is documented as "write CS2Video.txt", but CS2 may
#: instead read the per-account copy under Steam's userdata tree. We write the
#: install-tree path, say so out loud, and let --video-path override it until
#: someone confirms on hardware (docs/reference/first-launch.md).
VIDEO_TXT_CAVEAT = ("the authoritative CS2Video.txt location under Wine is UNCONFIRMED; "
                    "if the black screen persists, copy this file next to the per-account "
                    "video settings in Steam's userdata tree and report which one worked")


def render_video_txt(rec: recipe_mod.Recipe) -> str:
    """CS2Video.txt - the documented black-screen workaround (T-009 step 2)."""
    disp = rec.display
    return (
        '"video.cfg"\n'
        "{\n"
        f'\t"setting.defaultres"\t\t"{disp.get("width", 1920)}"\n'
        f'\t"setting.defaultresheight"\t\t"{disp.get("height", 1080)}"\n'
        f'\t"setting.fullscreen"\t\t"{disp.get("fullscreen", 0)}"\n'
        '\t"setting.coop_fullscreen"\t\t"0"\n'
        f'\t"setting.hdr_enabled"\t\t"0"\n'
        "}\n"
    )


def csgo_cfg_dir() -> Optional[Path]:
    install = probe.cs2_install_dir()
    if not install:
        return None
    path = install / "game" / "csgo" / "cfg"
    return path if path.is_dir() else None


def apply(rec: recipe_mod.Recipe, write_cfg: bool = True, write_video: bool = False,
          dry_run: bool = False, video_path: Optional[Path] = None) -> Dict[str, Any]:
    rec.require_valid()
    written: List[str] = []
    env_path = env_script_path(rec.name)
    if not dry_run:
        env_path.parent.mkdir(parents=True, exist_ok=True)
        env_path.write_text(render_env_script(rec))
        env_path.chmod(0o755)
    written.append(str(env_path))

    cfg_dir = csgo_cfg_dir()
    cfg_written: Optional[str] = None
    if write_cfg and cfg_dir:
        target = cfg_dir / CFG_NAME
        if not dry_run:
            target.write_text(render_cfg(rec))
        cfg_written = str(target)
        written.append(cfg_written)

    video_written: Optional[str] = None
    if write_video and (cfg_dir or video_path):
        target = Path(video_path) if video_path else (cfg_dir / "CS2Video.txt")
        if not dry_run:
            target.parent.mkdir(parents=True, exist_ok=True)
        if not dry_run:
            target.write_text(render_video_txt(rec))
        video_written = str(target)
        written.append(video_written)

    record = {
        "name": rec.name,
        "hash": rec.hash(),
        "source": rec.source,
        "applied": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "env_script": str(env_path),
        "cfg": cfg_written,
        "video_txt": video_written,
        "launch_options": rec.launch_options,
        "env": rec.env,
    }
    if not dry_run:
        write_json(active_path(), record)
    return {"record": record, "written": written, "dry_run": dry_run,
            "cfg_dir": str(cfg_dir) if cfg_dir else None}


def active_check() -> Check:
    record = active()
    if not record:
        return Check(id="profile", label="Active profile", status=WARN,
                     detail="no profile applied", fix="cs2kit config apply balanced-1080p",
                     task="T-027")
    try:
        rec = recipe_mod.resolve(record.get("name"))
    except recipe_mod.RecipeError:
        return Check(id="profile", label="Active profile", status=WARN,
                     detail=f"{record.get('name')} is applied but no longer exists",
                     fix="cs2kit config apply balanced-1080p", task="T-027")
    if rec.hash() != record.get("hash"):
        return Check(id="profile", label="Active profile", status=WARN,
                     detail=f"{rec.name} changed since it was applied",
                     fix=f"cs2kit config apply {rec.name}", task="T-027")
    return Check(id="profile", label="Active profile", status=PASS,
                 detail=f"{rec.name} ({rec.hash()})", task="T-027")


# --- CLI ---------------------------------------------------------------------
def cmd_list(args) -> int:
    rows = []
    for path in recipe_mod.list_profiles():
        try:
            rec = recipe_mod.load(path)
            rows.append({"name": rec.name, "kind": rec.kind, "path": str(path),
                         "description": rec.data.get("description", ""),
                         "problems": rec.validate()})
        except recipe_mod.RecipeError as exc:
            rows.append({"name": path.stem, "kind": "?", "path": str(path),
                         "description": str(exc), "problems": [str(exc)]})
    current = active().get("name")
    if args.json:
        print(json.dumps({"active": current, "profiles": rows}, indent=2, sort_keys=True))
        return EXIT_OK
    for row in rows:
        mark = "*" if row["name"] == current else " "
        flag = "" if not row["problems"] else "  [INVALID] " + "; ".join(row["problems"])
        print(f" {mark} {row['name']:<28} {row['kind']:<8} {row['description']}{flag}")
    print("\n* = active. Apply with: cs2kit config apply <name>")
    return EXIT_OK


def cmd_show(args) -> int:
    try:
        rec = recipe_mod.resolve(args.profile)
    except recipe_mod.RecipeError as exc:
        return emit_error("config show", str(exc), json_mode=args.json)
    if args.json:
        print(json.dumps({"name": rec.name, "hash": rec.hash(), "source": rec.source,
                          "data": rec.data, "problems": rec.validate()}, indent=2, sort_keys=True))
        return EXIT_OK
    print(rec.dumps().rstrip())
    problems = rec.validate()
    if problems:
        print("\nProblems:")
        for problem in problems:
            print(f"  - {problem}")
    return EXIT_OK


def cmd_apply(args) -> int:
    try:
        rec = recipe_mod.resolve(args.profile)
        result = apply(rec, write_cfg=not args.no_cfg, write_video=args.video,
                       dry_run=args.dry_run,
                       video_path=Path(args.video_path) if args.video_path else None)
    except recipe_mod.RecipeError as exc:
        return emit_error("config apply", str(exc), json_mode=args.json)
    if args.json:
        print(json.dumps(result, indent=2, sort_keys=True))
        return EXIT_OK
    record = result["record"]
    print(f"Applied {record['name']} ({record['hash']}){' [dry run]' if args.dry_run else ''}")
    for path in result["written"]:
        print(f"  wrote {path}")
    if record["video_txt"]:
        print(f"  note: {VIDEO_TXT_CAVEAT}")
    if not result["cfg_dir"]:
        print("  note: CS2 is not installed yet, so no game cfg was written (T-008)")
    print("\nSteam > CS2 > Properties > Launch Options:")
    print("  " + " ".join(record["launch_options"]))
    print(f"\nShell: source {record['env_script']}")
    if result["cfg_dir"]:
        print(f"Add to autoexec.cfg: exec {CFG_NAME[:-4]}")
    return EXIT_OK


def cmd_diff(args) -> int:
    try:
        rec = recipe_mod.resolve(args.profile)
    except recipe_mod.RecipeError as exc:
        return emit_error("config diff", str(exc), json_mode=args.json)
    record = active()
    fields = {"env": rec.env, "launch_options": rec.launch_options}
    drift = {k: {"expected": v, "actual": record.get(k)} for k, v in fields.items()
             if record.get(k) != v}
    if args.json:
        print(json.dumps({"profile": rec.name, "active": record.get("name"), "drift": drift},
                         indent=2, sort_keys=True))
    elif not record:
        print("No profile has been applied yet.")
    elif drift:
        print(f"{rec.name} differs from what was applied ({record.get('name')}):")
        for key, value in drift.items():
            print(f"  {key}\n    profile {value['expected']}\n    applied {value['actual']}")
    else:
        print(f"{rec.name} matches the applied configuration.")
    return EXIT_OK


def register(subparsers) -> None:
    parser = subparsers.add_parser(
        "config", help="apply a situational profile (T-027)",
        description="Profiles are overlays of env vars, launch options, cvars and resolution. "
                    "They never modify game binaries.")
    sub = parser.add_subparsers(dest="config_cmd")

    p = sub.add_parser("list", help="list shipped profiles")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=cmd_list)

    p = sub.add_parser("show", help="print a profile")
    p.add_argument("profile", nargs="?")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=cmd_show)

    p = sub.add_parser("apply", help="apply a profile")
    p.add_argument("profile")
    p.add_argument("--no-cfg", action="store_true", help="do not write the game cfg")
    p.add_argument("--video", action="store_true",
                   help="also write CS2Video.txt (the black-screen workaround, T-009)")
    p.add_argument("--video-path", help="write CS2Video.txt here instead (its true location "
                                        "under Wine is unconfirmed)")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=cmd_apply)

    p = sub.add_parser("diff", help="compare a profile with what is applied")
    p.add_argument("profile", nargs="?")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=cmd_diff)

    parser.set_defaults(func=cmd_list, json=False, video_path=None)
